global using BibliotekaOSP.Encje;
global using BibliotekaOSP.Interfejsy;
global using BibliotekaOSP.ModeleDto;
global using BibliotekaOSP.Modele;
global using BibliotekaOSP.Narzędzia;
global using BibliotekaOSP.Enumy;
global using BibliotekaOSP;
global using WebAppOSP.Services;
global using WebAppOSP.Controllers;